DROP TABLE Asistencia CASCADE CONSTRAINTS 
;

DROP TABLE Beneficio CASCADE CONSTRAINTS 
;

DROP TABLE Característica CASCADE CONSTRAINTS 
;

DROP TABLE Cerveza CASCADE CONSTRAINTS 
;

DROP TABLE Cerveza_Caracteristica CASCADE CONSTRAINTS 
;

DROP TABLE Cerveza_Presentacion CASCADE CONSTRAINTS 
;

DROP TABLE Cheque CASCADE CONSTRAINTS 
;

DROP TABLE Cliente CASCADE CONSTRAINTS 
;

DROP TABLE Cliente_Punto CASCADE CONSTRAINTS 
;

DROP TABLE Compra CASCADE CONSTRAINTS 
;

DROP TABLE Compra_Estatus CASCADE CONSTRAINTS 
;

DROP TABLE Compra_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Correo_Electrónico CASCADE CONSTRAINTS 
;

DROP TABLE Crédito CASCADE CONSTRAINTS 
;

DROP TABLE Cuota CASCADE CONSTRAINTS 
;

DROP TABLE Débito CASCADE CONSTRAINTS 
;

DROP TABLE Departamento CASCADE CONSTRAINTS 
;

DROP TABLE Descuento CASCADE CONSTRAINTS 
;

DROP TABLE Descuento_Inventario CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Compra CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Física CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Online CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_VentaE CASCADE CONSTRAINTS 
;

DROP TABLE Efectivo CASCADE CONSTRAINTS 
;

DROP TABLE Empleado CASCADE CONSTRAINTS 
;

DROP TABLE Empleado_Beneficio CASCADE CONSTRAINTS 
;

DROP TABLE Entrada_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Estatus CASCADE CONSTRAINTS 
;

DROP TABLE Evento CASCADE CONSTRAINTS 
;

DROP TABLE Horario CASCADE CONSTRAINTS 
;

DROP TABLE Ingrediente CASCADE CONSTRAINTS 
;

DROP TABLE Instruccion CASCADE CONSTRAINTS 
;

DROP TABLE Instruccion_Receta CASCADE CONSTRAINTS 
;

DROP TABLE Inventario CASCADE CONSTRAINTS 
;

DROP TABLE Inventario_E_Cerveza_P CASCADE CONSTRAINTS 
;

DROP TABLE Juez CASCADE CONSTRAINTS 
;

DROP TABLE Juez_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Jurídico CASCADE CONSTRAINTS 
;

DROP TABLE Lugar CASCADE CONSTRAINTS 
;

DROP TABLE Lugar_Tienda CASCADE CONSTRAINTS 
;

DROP TABLE Método_Pago CASCADE CONSTRAINTS 
;

DROP TABLE Natural CASCADE CONSTRAINTS 
;

DROP TABLE Orden_Reposición CASCADE CONSTRAINTS 
;

DROP TABLE OrdenR_Estatus CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Compra_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Pago_CompraP CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Cuota CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Entrada CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Fisica CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Online CASCADE CONSTRAINTS 
;

DROP TABLE Permiso CASCADE CONSTRAINTS 
;

DROP TABLE Persona_Contacto CASCADE CONSTRAINTS 
;

DROP TABLE Presentación CASCADE CONSTRAINTS 
;

DROP TABLE Privilegio CASCADE CONSTRAINTS 
;

DROP TABLE Proveedor CASCADE CONSTRAINTS 
;

DROP TABLE Punto CASCADE CONSTRAINTS 
;

DROP TABLE Receta CASCADE CONSTRAINTS 
;

DROP TABLE Receta_Ingrediente CASCADE CONSTRAINTS 
;

DROP TABLE Rol CASCADE CONSTRAINTS 
;

DROP TABLE Rol_Permiso CASCADE CONSTRAINTS 
;

DROP TABLE Rol_Privilegio CASCADE CONSTRAINTS 
;

DROP TABLE Tasa_Cambio CASCADE CONSTRAINTS 
;

DROP TABLE Teléfono CASCADE CONSTRAINTS 
;

DROP TABLE Tienda_Física CASCADE CONSTRAINTS 
;

DROP TABLE Tienda_Online CASCADE CONSTRAINTS 
;

DROP TABLE Tipo_Cerveza CASCADE CONSTRAINTS 
;

DROP TABLE Tipo_Cerveza_Caracteristica CASCADE CONSTRAINTS 
;

DROP TABLE Tipo_Empleado CASCADE CONSTRAINTS 
;

DROP TABLE Tipo_Evento CASCADE CONSTRAINTS 
;

DROP TABLE TipoE_Departamento CASCADE CONSTRAINTS 
;

DROP TABLE TipoED_Horario CASCADE CONSTRAINTS 
;

DROP TABLE Usuario CASCADE CONSTRAINTS 
;

DROP TABLE Vacación CASCADE CONSTRAINTS 
;

DROP TABLE Vacacion_Estatus CASCADE CONSTRAINTS 
;

DROP TABLE Venta_Entrada CASCADE CONSTRAINTS 
;

DROP TABLE Venta_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Venta_Física CASCADE CONSTRAINTS 
;

DROP TABLE Venta_Online CASCADE CONSTRAINTS 
;

DROP TABLE VentaF_Estatus CASCADE CONSTRAINTS 
;

DROP TABLE VentaO_Estatus CASCADE CONSTRAINTS 
;